"""
Certificate Generation - PDF Creation
"""

from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from datetime import datetime
import os

def generate_certificate(student_name, event_title, event_date, organizer_name, output_path):
    """
    Generate PDF certificate for event attendance
    
    Args:
        student_name: Name of the student
        event_title: Title of the event
        event_date: Date of the event
        organizer_name: Name of the organizer
        output_path: Path to save the PDF
    """
    # Create PDF in landscape mode
    c = canvas.Canvas(output_path, pagesize=landscape(letter))
    width, height = landscape(letter)

    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Colors
    primary = colors.HexColor('#0b3d91')
    accent = colors.HexColor('#f59e0b')
    text = colors.HexColor('#1f2937')

    # Background border
    c.setStrokeColor(primary)
    c.setLineWidth(4)
    c.roundRect(0.4*inch, 0.4*inch, width-0.8*inch, height-0.8*inch, 12, stroke=1, fill=0)

    # Decorative header bar
    c.setFillColor(primary)
    c.rect(0.4*inch, height-1.05*inch, width-0.8*inch, 0.6*inch, stroke=0, fill=1)

    # College name
    c.setFillColor(colors.white)
    c.setFont('Helvetica-Bold', 18)
    c.drawCentredString(width/2, height-0.7*inch, 'COLLEGE OF ENGINEERING THALASSERY')

    # Large certificate title
    c.setFillColor(primary)
    c.setFont('Times-Bold', 34)
    c.drawCentredString(width/2, height-1.6*inch, 'Certificate of Participation')

    # Subtitle
    c.setFont('Helvetica', 12)
    c.setFillColor(text)
    c.drawCentredString(width/2, height-2.05*inch, 'This is to certify that')

    # Student name
    c.setFont('Times-BoldItalic', 30)
    c.setFillColor(primary)
    c.drawCentredString(width/2, height-2.65*inch, student_name)

    # Participated in
    c.setFont('Helvetica', 12)
    c.setFillColor(text)
    c.drawCentredString(width/2, height-3.15*inch, 'has successfully participated in')

    # Event title (wrapped if long)
    c.setFont('Helvetica-Bold', 18)
    c.setFillColor(accent)
    max_width = width - 3*inch
    # Simple wrap
    if c.stringWidth(event_title, 'Helvetica-Bold', 18) > max_width:
        words = event_title.split()
        mid = len(words)//2
        line1 = ' '.join(words[:mid])
        line2 = ' '.join(words[mid:])
        c.drawCentredString(width/2, height-3.6*inch, line1)
        c.drawCentredString(width/2, height-4.0*inch, line2)
        event_y = height-4.6*inch
    else:
        c.drawCentredString(width/2, height-3.6*inch, event_title)
        event_y = height-4.0*inch

    # Event date
    c.setFont('Helvetica', 12)
    c.setFillColor(text)
    try:
        c.drawCentredString(width/2, event_y, f"Held on: {event_date}")
    except Exception:
        c.drawCentredString(width/2, event_y, f"Date: {event_date}")

    # (Watermark removed per user request)

    # Signature area
    sig_x = width - 3.5*inch
    sig_y = 1.9*inch
    c.setStrokeColor(text)
    c.line(sig_x-0.2*inch, sig_y, sig_x+2.4*inch, sig_y)
    c.setFont('Helvetica-Bold', 12)
    c.setFillColor(text)
    c.drawCentredString(sig_x+1.1*inch, sig_y-0.3*inch, organizer_name)
    c.setFont('Helvetica', 10)
    c.drawCentredString(sig_x+1.1*inch, sig_y-0.6*inch, 'Event Organizer')

    # Issue date bottom-left
    c.setFont('Helvetica', 10)
    c.setFillColor(text)
    c.drawString(0.7*inch, 1.1*inch, f"Issued: {datetime.now().strftime('%B %d, %Y')}")

    # Footer
    c.setFont('Helvetica-Oblique', 9)
    c.setFillColor(colors.HexColor('#6b7280'))
    c.drawCentredString(width/2, 0.7*inch, "Generated by Campus Event Management System - College of Engineering Thalassery")

    c.save()
    return output_path
